/control/verbose 0
/control/saveHistory

/run/initialize
/vis/open OGL 600x600-0+0
/vis/viewer/set/lineSegmentsPerCircle 60

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume
/vis/viewer/set/viewpointVector -1 1 1
/vis/viewer/set/lightsVector 1 1 0

/vis/viewer/set/style surface
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/colourByDensity 1 g/cm3 .5 3 10 # left

#Add axes
/vis/scene/add/axes -100 -100 -100 100 mm
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/endOfEventAction accumulate

/vis/geometry/set/visibility World 0 false
